Add whois.md
NatalyaVinogradova/qa-automation-java pull request #1
Opened 2021-08-03 12:56 UTC by NatalyaVinogradova

Домашнее задание 1. Добавила новый файл whois.md

2021-08-03 13:32 UTC, yuri-kudryavtsev requested changes
Все отлично, ты большой молодец 👍 

Ты верно создала отдельную ветку, подготовила коммит и сформировала ПР, словом все поставленные условия задания выполнены 👍 

Однако, можно сделать whois.md чуть-чуть интереснее и интерактивнее, добавив туда форматирование. 
Выдели, пожалуйста, свое имя и фамилию жирным, а e-mail сделай кликабельной ссылкой (как это сделать можно посмотреть например тут - https://ru.wikipedia.org/wiki/Markdown) 😃 

Оформи это дело отдельным коммитом, придерживаясь правил, описанных ниже (этих правил мы придерживаемся на нашем проекте с автотестами):
- наш родной язык - русский, используем его в коммит-месседжах :)
- если коммит относится к какой-то задаче, то упоминаем его в коммите (например: 'Задание 1 - Добавлен файл whois.md') - так задача не потеряется в большой большой истории репозитория

Будет прям супер, если ты внесешь эти исправления до 5 августа.

2021-08-03 13:35 UTC, yuri-kudryavtsev commented on whois.md
> +Vinogradova Natalya
Выдели, пожалуйста, жирным :)

2021-08-03 13:35 UTC, yuri-kudryavtsev commented on whois.md
> +n.vinogradova@tinkoff.ru
А тут в виде ссылочки :)

2021-08-03 15:52 UTC, NatalyaVinogradova commented
Замечания исправлены. @yuri-kudryavtsev, посмотри, пожалуйста? :grinning:

2021-08-04 06:54 UTC, yuri-kudryavtsev approved these changes
Все супер! Молодец, так держать!

2021-08-04 06:54 UTC, merged