Задание 2. Создана папочная структура исходников, скомпилировано прил…
NatalyaVinogradova/qa-automation-java pull request #3
Opened 2021-08-08 18:54 UTC by NatalyaVinogradova

Задание 2. Скомпилировала приложение и разделила исходники и бинарники в разные папки.

2021-08-08 18:55 UTC, NatalyaVinogradova commented
Лучше поздно, чем никогда :smiley:

2021-08-09 09:20 UTC, yuri-kudryavtsev requested changes
Привет!

Отличная работа, молодец! 👍 

Ты выполнила задание очень точно, создала и расположила класс Printer.java в пакете com.tinkoff.edu, а MyApplication.java в корне проекта и скомпилировала, но есть два момента, на которых я хотел бы еще остановиться:

1. В реальных продуктах абсолютно **все** классы должны лежать в каком-нибудь пакете, поэтому я хотел бы тебя попросить перенести класс Printer в пакет "com.tinkoff.edu.helpers", а класс MyApplication в корневой пакет "com.tinkoff.edu"
2. У каждого класса должна быть "шапка" с указанием, кто создал этот класс и является автором, например: 
```
import com.tinkoff.edu.Printer;

/**
 * Created on 14.07.2021
 *
 * @author Yuri Kudryavtsev
 */
public class MyApplication {
```

Пожалуйста, внеси правки до 10 августа и присылай мне на повторное ревью 😃

2021-08-09 13:47 UTC, NatalyaVinogradova commented
Привет! Все замечания поправила ) Посмотри, пожалуйста?

2021-08-10 17:17 UTC, yuri-kudryavtsev approved these changes
Отлично! Молодец, так держать!

2021-08-10 17:17 UTC, merged