Задание 3. Удалены файлы MyApplication.java, Printer.java. Сгенериров…
NatalyaVinogradova/qa-automation-java pull request #4
Opened 2021-08-11 17:16 UTC by NatalyaVinogradova

Привет! Выполнила задание по третьему занятию: удалила файлы, созданные в предыдущих заданиях, сгенерировала новый maven-проект, добавила в .gitignore папку target. Посмотри, пожалуйста?

2021-08-12 07:01 UTC, yuri-kudryavtsev requested changes
Привет 😃

Молодец 👍 , ты хорошо потрудилась, удалила лишние файлы, сгенерировала проект Maven, но у тебя возникли небольшие трудности с gitignore и есть парочка замечаний по стилю кода.

Ниже (или выше) я оставил свои комментарии применительно к коду - постарайся исправить их до 13 августа.

2021-08-12 07:01 UTC, yuri-kudryavtsev commented on .gitignore
> +.target/
Почему решила добавить точку перед названием папки "target"?

Почитай внимательно про шаблоны .gitignore например тут https://www.atlassian.com/ru/git/tutorials/saving-changes/gitignore и скорректируй шаблон так, чтобы исключить папку "target".

2021-08-12 07:01 UTC, yuri-kudryavtsev commented on README.md
> -Автоматизация QA
Для чего потребовалось удалить файл? Верни, пожалуйста.

2021-08-12 07:01 UTC, yuri-kudryavtsev commented on app/src/main/java/com/tinkoff/edu/App.java
> +    public static void main( String[] args ){
Старайся соблюдать кодстайл и форматирование, не допускай лишних пробелов. В частности, обрати внимание на сигнатуру метода main - там два лишних пробела.

2021-08-12 07:01 UTC, yuri-kudryavtsev commented on app/src/main/java/com/tinkoff/edu/App.java
> +    public static void main( String[] args ){
Для автоматического форматирования в IDEA есть функция Reformat Code (Ctrl + Alt + L).

2021-08-12 07:01 UTC, yuri-kudryavtsev commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +    public void shouldAnswerWithTrue()
Запомни, открывающая фигурная скобка всегда ставится на уровне с названием метода, т.е правильно:
`public void shouldAnswerWithTrue() {`

2021-08-12 07:01 UTC, yuri-kudryavtsev commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        assertTrue( true );
Лишние пробелы.

2021-08-12 07:01 UTC, yuri-kudryavtsev commented on app/target/maven-archiver/pom.properties
> +#Created by Apache Maven 3.6.3
Удали из ПРа все файлы из папки target - они не попали бы в коммит, если бы файл .gitignore был настроен верно. Для IDEA есть отличный плагин для работы с игнором - напиши мне, я покажу :)

2021-08-12 09:00 UTC, NatalyaVinogradova commented on .gitignore
> +.target/
Скопипастила название папки .idea и по ее аналогии написала target) Исправила

2021-08-12 09:01 UTC, NatalyaVinogradova commented on README.md
> -Автоматизация QA
Когда удаляла все файлы из прошлых заданий, вообще всё удалила) Исправила.

2021-08-12 09:06 UTC, NatalyaVinogradova commented on app/src/main/java/com/tinkoff/edu/App.java
> +    public static void main( String[] args ){
Воспользовалась твоей подсказкой, отформатировала

2021-08-12 09:06 UTC, NatalyaVinogradova commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +    public void shouldAnswerWithTrue()
Запомнила, исправила.

2021-08-12 09:07 UTC, NatalyaVinogradova commented on app/src/test/java/com/tinkoff/edu/AppTest.java
> +        assertTrue( true );
Исправила.

2021-08-12 09:07 UTC, NatalyaVinogradova commented on app/target/maven-archiver/pom.properties
> +#Created by Apache Maven 3.6.3
Исправила)

2021-08-12 09:08 UTC, NatalyaVinogradova commented
Все замечания исправила!)

2021-08-13 13:21 UTC, yuri-kudryavtsev approved these changes
Отлично! Все сделано просто супер, молодец 👍

2021-08-13 13:21 UTC, merged