Задание 4. Добавлены новые классы для приложения Loan Scoring.
NatalyaVinogradova/qa-automation-java pull request #5
Opened 2021-08-13 16:56 UTC by NatalyaVinogradova

Привет! Выполнила задание по 4 занятию. Добавила новые классы для нового приложения.

2021-08-16 11:55 UTC, yuri-kudryavtsev requested changes
Молодец, ты отлично разбила приложение на контроллер, сервис и хранилище + добавила генерацию уникального ID для заказов 👍 

Чтобы было прям совсем супер, я бы хотел, чтобы ты поподробней проработала User Story из задания.

Я отписался подробнее в комментариях. 
Постарайся внести правки до 17 августа.

2021-08-16 11:55 UTC, yuri-kudryavtsev commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcController.java
> +    public static int createRequest() {
Давай рассмотрим нашу юзер-стори:

> Как клиент банка, я хочу сделать запрос на кредит и получить ответ с уникальным id для дальнейших коммуникаций

- Пользователь может быть как - клиентом банка, так и кем-то другим
- Клиент банка хочет сделать запрос на кредит - когда запрашиваем кредит, то как минимум указываем желаемую сумму кредита и срок кредитования

В связи с этим, в нашем методе createRequest должно быть как минимум 3 параметра:

1. уникальный номер пользователя (больше или равен 0 если это клиент, меньше нуля если это кто-то левый)
2. желаемая сумма (больше 0, но не больше какой-то константы, например 5 млн)
3. желаемый срок кредитования в месяцах (больше 0, но не больше, скажем 5 лет)

Добавь такие параметры + валидацию и логирование к методу createRequest.
Если валидация не проходит - нужно писать сообщение об ошибке и прекращать выполнение метода, если валидация пройдена - возвращаем уникальный номер заявки.
Валидацию легко можно сделать с помощью Assert-ов.

2021-08-16 11:55 UTC, yuri-kudryavtsev commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcLogger.java
> +    public static void log() {
Метод log очень скучный, он выводит только calling...

Давай параметризируем его, добавим два параметра:
1. Тип события, String, eventType - будем туда передавать "Информация", "Предупреждение", "Ошибка"
2. Сообщение, String, message - там будет непосредственно текст сообщения

А в самом методе будем форматировать текст, например так: 
`System.out.println(eventType + ": " + message);`

2021-08-16 11:55 UTC, yuri-kudryavtsev commented on app/src/main/java/com/tinkoff/edu/app/LoanCalcRepository.java
> +    private static int requestId;
Хоть такая конструкция и допускается в языке Java, но статическим переменным лучше явно задавать значения при их объявлении, например так:
`private static int requestId = 0;`

Мы таким образом исключаем недосказанность + разработчик явно видит, какое начальное значение у переменной.

2021-08-16 11:55 UTC, yuri-kudryavtsev commented on app/src/main/java/com/tinkoff/edu/test/LoanCalcTest.java
> +        System.out.println(requestId + " must be 1");
Поменяй, пожалуйста,  `System.out.println(requestId + " must be 1");` на Assert.

2021-08-18 13:24 UTC, NatalyaVinogradova commented
Договорились, что правки внесу в следующее домашнее задание.

2021-08-20 08:30 UTC, merged